/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package createGameLobbyWindowAndAction;

import GameWindow.ShowMapAction;
import GameWindow.SimulatorFrame;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.server.UnicastRemoteObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import Interfaces.Client;
import Interfaces.Connection;


public class CreateGameLobby extends javax.swing.JDialog {

    private SimulatorFrame frame = SimulatorFrame.getInstance();
    /**
     * Creates new form StartDialog
     */
    public CreateGameLobby(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setBounds(50, 50, 400, 250);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Player = new javax.swing.ButtonGroup();
        jRadioButton_1Player = new javax.swing.JRadioButton();
        jRadioButton_2Player = new javax.swing.JRadioButton();
        jRadioButton_3Player = new javax.swing.JRadioButton();
        jRadioButton_4Player = new javax.swing.JRadioButton();
        jRadioButton_5Player = new javax.swing.JRadioButton();
        jButton_Continue = new javax.swing.JButton();
        jLabel_GameName = new javax.swing.JLabel();
        jTextField_GameName = new javax.swing.JTextField();
        jTextField_GameCode = new javax.swing.JTextField();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_GameCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup_Player.add(jRadioButton_1Player);
        jRadioButton_1Player.setText("1 Player");
        getContentPane().add(jRadioButton_1Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        buttonGroup_Player.add(jRadioButton_2Player);
        jRadioButton_2Player.setText("2 Player");
        jRadioButton_2Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_2PlayerActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_2Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        buttonGroup_Player.add(jRadioButton_3Player);
        jRadioButton_3Player.setText("3 Player");
        getContentPane().add(jRadioButton_3Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        buttonGroup_Player.add(jRadioButton_4Player);
        jRadioButton_4Player.setText("4 Player");
        getContentPane().add(jRadioButton_4Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        buttonGroup_Player.add(jRadioButton_5Player);
        jRadioButton_5Player.setText("5 Player");
        jRadioButton_5Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_5PlayerActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_5Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jButton_Continue.setAction(new createGameLobbyWindowAndAction.CreateGameAction());
        jButton_Continue.setText("Create ");
        getContentPane().add(jButton_Continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 207, -1, -1));

        jLabel_GameName.setText("Game-Name:");
        jLabel_GameName.setToolTipText("");
        getContentPane().add(jLabel_GameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 86, 88, 28));
        getContentPane().add(jTextField_GameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 235, 28));
        getContentPane().add(jTextField_GameCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 235, 28));

        jLabel_Title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Title.setText("Create Game-Server");
        getContentPane().add(jLabel_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        jLabel_GameCode.setText("Game-Code:");
        getContentPane().add(jLabel_GameCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 88, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_2PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_2PlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_2PlayerActionPerformed

    private void jRadioButton_5PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_5PlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_5PlayerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Player;
    private javax.swing.JButton jButton_Continue;
    private javax.swing.JLabel jLabel_GameCode;
    private javax.swing.JLabel jLabel_GameName;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JRadioButton jRadioButton_1Player;
    private javax.swing.JRadioButton jRadioButton_2Player;
    private javax.swing.JRadioButton jRadioButton_3Player;
    private javax.swing.JRadioButton jRadioButton_4Player;
    private javax.swing.JRadioButton jRadioButton_5Player;
    private javax.swing.JTextField jTextField_GameCode;
    private javax.swing.JTextField jTextField_GameName;
    // End of variables declaration//GEN-END:variables

    public ButtonGroup getButtonGroup_Player() {
        return buttonGroup_Player;
    }

    public void setButtonGroup_Player(ButtonGroup buttonGroup_Player) {
        this.buttonGroup_Player = buttonGroup_Player;
    }

    public JRadioButton getjRadioButton_1Player() {
        return jRadioButton_1Player;
    }

    public void setjRadioButton_1Player(JRadioButton jRadioButton_1Player) {
        this.jRadioButton_1Player = jRadioButton_1Player;
    }

    public JRadioButton getjRadioButton_2Player() {
        return jRadioButton_2Player;
    }

    public void setjRadioButton_2Player(JRadioButton jRadioButton_2Player) {
        this.jRadioButton_2Player = jRadioButton_2Player;
    }

    public JRadioButton getjRadioButton_3Player() {
        return jRadioButton_3Player;
    }

    public void setjRadioButton_3Player(JRadioButton jRadioButton_3Player) {
        this.jRadioButton_3Player = jRadioButton_3Player;
    }

    public JRadioButton getjRadioButton_4Player() {
        return jRadioButton_4Player;
    }

    public void setjRadioButton_4Player(JRadioButton jRadioButton_4Player) {
        this.jRadioButton_4Player = jRadioButton_4Player;
    }

    public JRadioButton getjRadioButton_5Player() {
        return jRadioButton_5Player;
    }

    public void setjRadioButton_5Player(JRadioButton jRadioButton_5Player) {
        this.jRadioButton_5Player = jRadioButton_5Player;
    }

    public JTextField getjTextField_GameCode() {
        return jTextField_GameCode;
    }

    public void setjTextField_GameCode(JTextField jTextField_GameCode) {
        this.jTextField_GameCode = jTextField_GameCode;
    }

    public JTextField getjTextField_GameName() {
        return jTextField_GameName;
    }

    public void setjTextField_GameName(JTextField jTextField_GameName) {
        this.jTextField_GameName = jTextField_GameName;
    }

    public int calcPlayerCount(){
        if (frame.createGameLobbyWindow.getjRadioButton_5Player().isSelected()) {
            return 5;
        } else if (frame.createGameLobbyWindow.getjRadioButton_4Player().isSelected()) {
            return 4;
        } else if (frame.createGameLobbyWindow.getjRadioButton_3Player().isSelected()) {
            return 3;
        } else if (frame.createGameLobbyWindow.getjRadioButton_2Player().isSelected()) {
            return 2;
        } else {
            return 1;
        }
    }
    
   
}
